import { Injectable, InternalServerErrorException } from '@nestjs/common';
import OpenAI from 'openai';
import 'dotenv/config';

@Injectable()
export class AiService {
  private readonly client = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
    project: process.env.OPENAI_PROJECT_ID,
  });

  async generateStructuredOutput(params: {
    systemPrompt: string;
    userPrompt: string;
    schemaName: string;
  }): Promise<unknown> {
    try {
      const response = await this.client.chat.completions.create({
        model: 'gpt-4.1-mini',
        messages: [
          { role: 'system', content: params.systemPrompt },
          { role: 'user', content: params.userPrompt },
        ],
        temperature: 0.4,
      });

      const content = response.choices[0]?.message?.content;

      if (!content) {
        throw new InternalServerErrorException(
          'Unable to generate workout at the moment.',
        );
      }

      try {
        return JSON.parse(content);
      } catch {
        throw new InternalServerErrorException(
          'Invalid workout response generated by AI.',
        );
      }
    } catch (error) {
      if (error instanceof InternalServerErrorException) throw error;
      throw new InternalServerErrorException(
        'Unable to generate workout at the moment.',
      );
    }
  }
}
