import { BadRequestException, Injectable } from '@nestjs/common';
import { workoutPlanSchema } from '../schemas/workout-plan.schema';
import { WorkoutPlan } from '../schemas/workout-plan.schema';

@Injectable()
export class WorkoutOutputValidatorService {
  validate(output: unknown): WorkoutPlan {
    const parsed = workoutPlanSchema.safeParse(output);

    if (!parsed.success) {
      throw new BadRequestException(
        'Invalid workout response generated by AI.',
      );
    }

    return parsed.data;
  }
}
